### ISSUE TITLE
Enhancement: Keep Spots Header Row Visible

### ISSUE THREAD

**Issue by jgedmond** [cwhelchel/hunterlog#20]
Keep the Spots Table column headings from scrolling with the spots table entries so that the headings stay visible under the filters rows (hide QRT, hide hunted, etc).  In this way the headings will be available to sort the spots when you have scrolled down the Spots table.

 - Windows 10 Pro
 - Hunterlog version: 0.0.2
 - Hunterlog database version: 922a7b854b71

**Comment by cwhelchel** [comment]
Fix in [0771b40](https://github.com/cwhelchel/hunterlog/commit/0771b4021f3cb4a2e94b8d1dd688ecd3495674ec)
