### ISSUE TITLE
Saving of previous hunterlog window position

### ISSUE THREAD

**Issue by jgedmond** [cwhelchel/hunterlog#27]
Saving of the previous window size and position works well if I only use my laptop screen.  However, when I put the hunterlog window on the extended desktop screen, the position is not remembered.  upon opening again, window reverts to the laptop screen.

**Comment by cwhelchel** [comment]
In the previous version, I didn't save the location. only the size. I want to work in something to reset the config options to default in case something happens.

Also, i need to make sure the pywebview takes in the X and Y coords.
