### ISSUE TITLE
Omnirig please

### ISSUE THREAD

**Issue by pcpackrat** [cwhelchel/hunterlog#41]
Making a feature request for omnirig.  FLRig is not a happy camper with wsjtx or cw skimmer.

**Comment by pcpackrat** [comment]
Thanks. I know this isn't your issue, but Flrig is constantly changing the filters on my 7610. For example, all 3 of my filters end up being the same bandwidth after a while.

-Michael

On Sep 18, 2024 07:26, krinkle ***@***.***> wrote:

I'll see what I can do with this. I know that it would be Windows only as Omnirig is a COM component.

**Comment by pcpackrat** [comment]
You know what? its not omnirig I want.  I am going to close this as I was dependent on the ham-apps-proxy.  I need to re-engineer the way I do things.

**Comment by cwhelchel** [comment]
@pcpackrat try different versions of flrig. I know I had crashes and finally settled on version 2.0.01 for my ic 7300. I also have issues with FLRIG changing the filters I just kinda deal with it.
